# Generated by Django 3.0.5 on 2023-06-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportf', '0002_auto_20230624_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
